---
name: Review

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: The pull request number to approve
        required: true
      state:
        type: choice
        description: Whether to approve or request changes on pull request.
        options: 
        - approve
        - request_changes

jobs:
  approve:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Approve pull request
        run: gh pr review ${{ inputs.pr_number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ inputs.state == 'approve' }}

      - name: Request changes on pull request
        run: gh pr review ${{ inputs.pr_number }} --request-changes -b "needs more work"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ inputs.state == 'request_changes' }}