name: black
on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Code linting
        uses: ansible-network/github_actions/.github/actions/tox@main
        with:
          path: "."
          tox_envlist: black