name: Merge

on:
  workflow_run:
    workflows: [black]
    types:
      - completed

jobs:
  merge:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Dump github action context
        uses: crazy-max/ghaction-dump-context@v2