name: CI
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [black]
    types:
      - completed

jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: mergeit
          MERGE_METHOD: squash